version: v1
plugins:
  - plugin: buf.build/grpc-ecosystem/openapiv2:v2.16.2
    out: dist/openapi
    opt:
      - logtostderr=true
      - json_names_for_fields=false
      - generate_unbound_methods=true